£ifndef REXXCOM_H_INCLUDED
£define REXXCOM_H_INCLUDED

£pragma runopts(PLIST(OS))
/*
typedef struct rexxParm_t È
short parm_len;
char parm_data›~;
Ë rexxParm_t;
*/
int rexxArgs();
int getArgsRexx();

extern int    argc;                 /* nombre d'arguments  */
extern int    cursc;                /* position colonne de cursor */
extern int    cursl;                /* position ligne   de cursor */
extern char   rawcode›20000~›81~;   /* code Cobol brute           */
extern int    lnumlast;             /* numero de la derniere ligne*/
extern char*  mainret;              /* zone retour                */

extern int    curr_ln_num;          /* current line being parsed  */
£endif
/* REXXCOM_H_INCLUDED */
